attach if not exists 'dbname=sidra user=sidra password=test host=localhost' as sidra_client (type postgres);

-- now we create the tables for the fully centralized example
CREATE TABLE IF NOT EXISTS sidra_client.sidra_staging_view_activity_sessions (
    username TEXT,
    nickname TEXT,
    city TEXT,
    day TEXT,
    start_time TEXT,
    end_time TEXT,
    steps INTEGER,
    heartbeat_rate INTEGER,
    generation TIMESTAMPTZ,
    arrival TIMESTAMPTZ,
    sidra_window INT,
    client_id BIGINT,
    action SMALLINT);

-- equivalent of daily_steps_user to test in a fully centralized architecture
-- instructions generated by OpenIVM
create table if not exists centralized_daily_steps_user as
select nickname, city, day, sum(steps) as total_steps
from sidra_client.sidra_staging_view_activity_sessions
group by nickname, city, day;

-- equivalent of daily_steps to test in a fully centralized architecture
create table if not exists centralized_daily_steps as
select city, day, sum(total_steps) as total_steps
from centralized_daily_steps_user
group by city, day;

-- leaderboard table for the fully centralized architecture
create table if not exists centralized_leaderboard as
select nickname, sum(total_steps) as total_steps
from centralized_daily_steps_user
where nickname is not null
group by nickname;

-- manually creating delta tables now (to simplify reproducibility)
-- delta table for the staging area
create table if not exists sidra_client._delta_sidra_staging_view_activity_sessions as
select nickname, city, day, steps, sidra_window, client_id,
true as _duckdb_ivm_multiplicity, now() as _duckdb_ivm_timestamp
from sidra_client.sidra_staging_view_activity_sessions limit 0;

create table if not exists _delta_centralized_daily_steps_user as 
select nickname, city, day, total_steps, true as _duckdb_ivm_multiplicity, now() as _duckdb_ivm_timestamp
from sidra_client.sidra_staging_view_daily_steps_user limit 0;
create table if not exists _delta_centralized_daily_steps as 
select *, true as _duckdb_ivm_multiplicity, now() as _duckdb_ivm_timestamp
from centralized_daily_steps limit 0;

create table if not exists _delta_centralized_leaderboard as
select nickname, total_steps, true as _duckdb_ivm_multiplicity, now() as _duckdb_ivm_timestamp
from centralized_leaderboard limit 0;

create unique index if not exists centralized_daily_steps_user_ivm_index on centralized_daily_steps_user(nickname, city, day);
create unique index if not exists centralized_daily_steps_ivm_index on centralized_daily_steps(day);
create unique index if not exists centralized_leaderboard_ivm_index on centralized_leaderboard(nickname);

-- IVM metadata scripts
CREATE TABLE IF NOT EXISTS _duckdb_ivm_delta_tables (
    view_name
    VARCHAR,
    table_name
    VARCHAR,
    last_update
    TIMESTAMP);

-- dropping the delta tables
DROP TABLE IF EXISTS sidra_client.delta_sidra_staging_view_activity_sessions;
DROP TABLE IF EXISTS delta_centralized_daily_steps_user;
DROP TABLE IF EXISTS delta_centralized_daily_steps;
DROP TABLE IF EXISTS delta_centralized_leaderboard;

-- Create timestamp tracking tables
CREATE TABLE IF NOT EXISTS _duckdb_ivm_views (
                                                 view_name VARCHAR PRIMARY KEY,
                                                 sql_string VARCHAR,
                                                 type TINYINT,
                                                 last_update TIMESTAMP
);

CREATE TABLE IF NOT EXISTS _duckdb_ivm_delta_tables (
    view_name VARCHAR,
    table_name VARCHAR,
    last_update TIMESTAMP,
    PRIMARY KEY(view_name, table_name)
    );

-- Initialize timestamp tracking entries
INSERT OR REPLACE INTO _duckdb_ivm_views VALUES 
    ('daily_steps', 'select city, day, sum(total_steps) as total_steps from daily_steps_user group by city, day', 0, NOW()),
    ('leaderboard', 'select nickname, sum(total_steps) as total_steps from daily_steps_user where nickname is not null group by nickname', 0, NOW());

INSERT OR REPLACE INTO _duckdb_ivm_delta_tables VALUES 
    ('daily_steps', '_delta_daily_steps', NOW()),
    ('leaderboard', '_delta_leaderboard', NOW());

.q